CREATE TABLE IF NOT EXISTS "student" (
"person_id" VARCHAR(36) NOT NULL PRIMARY KEY,
"entry_date_time" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
"group_id" VARCHAR(36),
FOREIGN KEY ("person_id")
REFERENCES "person"("id")
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY ("group_id")
REFERENCES "student_group"("id")
ON DELETE SET NULL
ON UPDATE CASCADE
);