CREATE TABLE IF NOT EXISTS "mark" (
"id" VARCHAR(36) NOT NULL PRIMARY KEY,
"subject_id" VARCHAR(36) NOT NULL,
"mark_value" INTEGER NOT NULL,
"student_id" VARCHAR(36) NOT NULL,
FOREIGN KEY ("subject_id")
REFERENCES "subject"("id")
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY ("student_id")
REFERENCES "student"("person_id")
ON DELETE CASCADE
ON UPDATE CASCADE
);